          name: Deploy to DigitalOcean

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        env:
          PROJECT_DIRECTORY: ${{ secrets.PROJECT_DIRECTORY }}
          TARGET_DIRECTORY: ${{ secrets.TARGET_DIRECTORY }}
          HOST: ${{ secrets.DROPLET_IP }}
          USERNAME: ${{ secrets.DROPLET_USER }}
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying to DigitalOcean droplet..."
            
            # Navigate to project directory
            cd $PROJECT_DIRECTORY

            # Rsync files to the droplet
            rsync -avz --delete ./ $USERNAME@$HOST:$TARGET_DIRECTORY 
            
            echo "Directory overwritten successfully."
