name: Deploy to DigitalOcean

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean
        env:
          project_directory: ${{ secrets.PROJECT_DIRECTORY }}
          target_directory: ${{ secrets.TARGET_DIRECTORY }}
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            cd $project_directory
            mkdir -p $directory
            # Rsync files to the droplet
            rsync -avz --delete ./ root@$host:$target_directory

      - name: Update Git repository
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update deployed files"
            git push
