name: Deploy to DigitalOcean

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Linux System
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          TARGET_DIRECTORY: ${{ secrets.TARGET_DIRECTORY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            echo "Deploying to DigitalOcean droplet..."

            # Rsync files to the Linux system
            rsync -avz --delete ./ $USER@$HOST:$TARGET_DIRECTORY
            echo "Directory overwritten successfully."
