name: Deploy to Server

on:
  push:
    branches:
      - development 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Transfer files to server
        env:
          HOST: ${{ secrets.DROPLET_IP }}
          USER: ${{ secrets.DROPLET_USER }}
          TARGET: ${{ secrets.TARGET_DIRECTORY }}
        run: |
          rsync -avz --delete ./ $USER@$HOST:$TARGET
